### ISSUE TITLE
Too many tabs?

### ISSUE THREAD

**Issue by theveug** [Corbris/POE_Horticrafting_Tracker#1]
After reaching tab 66 this drops

```
(node:12032) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at createCraftStructs (C:\snapshot\POE_Horticrafting_Tracker\POE_Horticrafting_Tracker.js:97:22)
    at C:\snapshot\POE_Horticrafting_Tracker\POE_Horticrafting_Tracker.js:78:17
    at Array.forEach (<anonymous>)
    at C:\snapshot\POE_Horticrafting_Tracker\POE_Horticrafting_Tracker.js:77:30
    at Array.forEach (<anonymous>)
    at forEachCraft (C:\snapshot\POE_Horticrafting_Tracker\POE_Horticrafting_Tracker.js:75:21)
    at getALLhorticraftItems (C:\snapshot\POE_Horticrafting_Tracker\POE_Horticrafting_Tracker.js:71:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:12032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)```

**Comment by Corbris** [comment]
The latest update has broken the way I was parsing all the crafts. Im currently working on a full overhaul that will fix this issue.

**Comment by Corbris** [comment]
Issues were fixed in v2.0.0 https://github.com/Corbris/POE_Horticrafting_Tracker/releases/tag/v2.0.0

**Comment by theveug** [comment]
Now its too many requests?

```
Fetching tab  0
Fetching tab  1
Fetching tab  2
Fetching tab  3
Fetching tab  4
Fetching tab  5
Fetching tab  6
Fetching tab  7
Fetching tab  8
Fetching tab  9
Fetching tab  10
Fetching tab  11
Fetching tab  12
Fetching tab  13
Fetching tab  14
Fetching tab  15
Fetching tab  16
Fetching tab  17
Fetching tab  18
Fetching tab  19
Fetching tab  20
Fetching tab  21
Fetching tab  22
Fetching tab  23
Fetching tab  24
Fetching tab  25
Fetching tab  26
Fetching tab  27
Fetching tab  28
Fetching tab  29
Fetching tab  30
Fetching tab  31
Fetching tab  32
Fetching tab  33
Fetching tab  34
Fetching tab  35
Fetching tab  36
Fetching tab  37
Fetching tab  38
Fetching tab  39
Fetching tab  40
Fetching tab  41
Fetching tab  42
Fetching tab  43
Fetching tab  44
Fetching tab  45
Fetching tab  46
Fetching tab  47
Fetching tab  48
Fetching tab  49
Fetching tab  50
Fetching tab  51
Fetching tab  52
Fetching tab  53
Fetching tab  54
Fetching tab  55
Fetching tab  56
Fetching tab  57
Fetching tab  58
Fetching tab  59
Fetching tab  60
Fetching tab  61
Fetching tab  62
Fetching tab  63
Fetching tab  64
Fetching tab  65
Fetching tab  66
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
ERROR: Too Many Requests
failed to fetch Items
```

**Comment by Corbris** [comment]
After looking into this the POE api limits you are limited to 45 request per minute or you get timed out. 

I have added options in the config to request tabs by index or name.
If these are left blank it will search all tabs. 
If you are requesting more then 43 tabs then the request will be spaced out 1.4 seconds to not hit the rate limit

https://github.com/Corbris/POE_Horticrafting_Tracker/releases

If you could verify that this works ill close the issue.

**Comment by theveug** [comment]
You beauty! working like a charm top job!!
